name: Release documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - 'main'



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildrelease:
    environment: services
    # The type of runner that the job will run on
    runs-on: lab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Steps represent a sequence of tasks that will be executed as part of the job

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main
        pre_release_branches: development, feature.*
        append_to_pre_release_tag: snap
        dry_run: true


    - name: "Get build info"
      id: build_info
      shell: bash
      run: |
        python -V
        pip list | grep
        release_body=`changelog ${GITHUB_REPOSITORY} -t ${{ github.token }} -sr v${{steps.tag_version.outputs.previous_tag}} -b main`
        release_body="${release_body//'%'/%25}"
        release_body="${release_body//$'\n'/%0A}"
        release_body="${release_body//$'\r'/%0D}"
        echo "##[set-output name=release_body;]$(echo ${release_body})"

    - name: "Create release"
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      with:
        tag_name: ${{steps.tag_version.outputs.new_tag}}
        release_name: Release ${{steps.tag_version.outputs.new_tag}}
        body: |
          ${{steps.build_info.outputs.release_body}}
        draft: false
        prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{steps.tag_version.outputs.new_tag}}

